export const PRODUCTS = [
    // Red Wines
    {
        id: 0,
        name: "Domaine La Vinsobraise",
        underName: "AOC Côtes du Rhône",
        image:"../assets/wines/red/domaineLaVinsobraise.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "wine",
        color: "red",
        region: "Rhône",
        price: "6.50 €",
        cepage: "Syrah / Grenache",
        millenium: "2019",
        alcohol: "14%",
        volume: "750ml"
    },
    {
        id: 1,
        name: "Domaine L'Abbé Dubois",
        underName: "Côtes du Vivarais",
        image:"../assets/wines/red/DomaineLAbbéDubois.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "wine",
        color: "red",
        region: "Rhône",
        price: "7.50 €",
        cepage: "Syrah / Grenache",
        millenium: "2017",
        alcohol: "13%",
        volume: "750ml"
    },

    // White Wines
    {
        id: 2,
        name: "Château CARBONNEAU",
        underName: "Cuvée Margot - Côtes de Bordeaux",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "wine",
        color: "white",
        region: "Bordeaux",
        price: "12.00 €",
        cepage: "Sauvignon",
        millenium: "2019",
        alcohol: "13%",
        volume: "750ml"
    },
    {
        id: 3,
        name: "Vignerons de Genouilly",
        underName: "Montagny 1er Cru - Bourgogne",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "wine",
        color: "white",
        region: "Bourgogne",
        price: "17.00 €",
        cepage: "Chardonnay",
        millenium: "2019",
        alcohol: "12.5%",
        volume: "750ml"
    },

    // Rosé Wines
    {
        id: 4,
        name: "Domaine Vigneret",
        underName: "Bandol",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "wine",
        color: "rose",
        region: "Provence",
        price: "16.00 €",
        cepage: "Mourvèdre / Grenache / Cinsault / Carignan",
        millenium: "2019",
        alcohol: "13.5%",
        volume: "750ml"
    },
    {
        id: 5,
        name: "Chaâteau Calissanne",
        underName: "Clos Victoire - Coteaux d'Aix en Provence",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "wine",
        color: "rose",
        region: "Provence",
        price: "14.00 €",
        cepage: "Syrah / Grenache",
        millenium: "2019",
        alcohol: "13%",
        volume: "750ml"
    },

    //Champagnes
    {
        id: 6,
        name: "Domaine Baud",
        underName: "Crémant du Jura - BRUT",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "champagne",
        color: "",
        region: "Jura",
        price: "14.00 €",
        cepage: "Chardonnay",
        millenium: "",
        alcohol: "12%",
        volume: "750ml"
    },
    {
        id: 7,
        name: "Domaine Dukatre",
        underName: "Premier cru - Extra-Brut-Blanc de Blancs",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "champagne",
        color: "",
        region: "",
        price: "55.00 €",
        cepage: "Chardonnay",
        millenium: "",
        alcohol: "12.5%",
        volume: "750ml"
    },

    //Digestives
    {
        id: 8,
        name: "Domaine BAUD",
        underName: "Macvin du Jura - Jura",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "digestif",
        color: "",
        region: "",
        price: "25.00 €",
        cepage: "Chardonnay / Vieux Marc",
        millenium: "",
        alcohol: "45%",
        volume: "620ml"
    },
    {
        id: 9,
        name: "Domaine BAUD",
        underName: "Vieux Marc - Jura",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "digestif",
        color: "",
        region: "",
        price: "38.00 €",
        cepage: "",
        millenium: "",
        alcohol: "45%",
        volume: "700ml"
    },

    //Oils
    {
        id: 10,
        name: "Château Calissanne - Font de leu",
        underName: "Huile d'olive d'Aix en Provence AOP",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "oil",
        color: "",
        region: "",
        price: "19.00 €",
        cepage: "Huile d'olive extra-vierge / Fruité vert",
        millenium: "",
        alcohol: "",
        volume: "500ml"
    },
    {
        id: 11,
        name: "Château Calissanne - Les merveilles",
        underName: "Huile d'olive d'Aix en Provence AOP",
        image:"../assets/vins.jpg",
        text: "Some quick example text to build on the card title and make up the bulk of the card's content.",
        category: "oil",
        color: "",
        region: "",
        price: "19.00 €",
        cepage: "Huile d'olive extra-vierge",
        millenium: "",
        alcohol: "",
        volume: "500ml"
    },
]